package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ACENTITY".
 */
public class ACEntity {

	private Long id;
	private int indexId;
	private int iconId;

	private String strText;
	private int address;

	public ACEntity() {
	}

	public ACEntity(Long id) {
		this.id = id;
	}

	public ACEntity(Long id, int indexId, int iconId, String strText,
			int address) {
		this.id = id;
		this.indexId = indexId;
		this.iconId = iconId;
		this.strText = strText;
		this.address = address;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getIndexId() {
		return indexId;
	}

	public void setIndexId(int indexId) {
		this.indexId = indexId;
	}

	public int getIconId() {
		return iconId;
	}

	public void setIconId(int iconId) {
		this.iconId = iconId;
	}

	public String getStrText() {
		return strText;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setStrText(String strText) {
		this.strText = strText;
	}

	public int getAddress() {
		return address;
	}

	public void setAddress(int address) {
		this.address = address;
	}

}
