package greendao;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SCENE_ENTITY".
 */
public class SceneEntity {

    private Long id;

    private String strText;
    private int iconId;
    private boolean isLight;
    private boolean isAC;
    private boolean isCurtain;
    private boolean isBgMusic;
    private boolean isPreTime;

    public SceneEntity() {
    }

    public SceneEntity(Long id) {
        this.id = id;
    }

    public SceneEntity(Long id, String strText, int iconId, boolean isLight, boolean isAC, boolean isCurtain, boolean isBgMusic, boolean isPreTime) {
        this.id = id;
        this.strText = strText;
        this.iconId = iconId;
        this.isLight = isLight;
        this.isAC = isAC;
        this.isCurtain = isCurtain;
        this.isBgMusic = isBgMusic;
        this.isPreTime = isPreTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStrText() {
        return strText;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStrText( String strText) {
        this.strText = strText;
    }

    public int getIconId() {
        return iconId;
    }

    public void setIconId(int iconId) {
        this.iconId = iconId;
    }

    public boolean getIsLight() {
        return isLight;
    }

    public void setIsLight(boolean isLight) {
        this.isLight = isLight;
    }

    public boolean getIsAC() {
        return isAC;
    }

    public void setIsAC(boolean isAC) {
        this.isAC = isAC;
    }

    public boolean getIsCurtain() {
        return isCurtain;
    }

    public void setIsCurtain(boolean isCurtain) {
        this.isCurtain = isCurtain;
    }

    public boolean getIsBgMusic() {
        return isBgMusic;
    }

    public void setIsBgMusic(boolean isBgMusic) {
        this.isBgMusic = isBgMusic;
    }

    public boolean getIsPreTime() {
        return isPreTime;
    }

    public void setIsPreTime(boolean isPreTime) {
        this.isPreTime = isPreTime;
    }

}
