package greendao;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCENE_ENTITY".
*/
public class SceneEntityDao extends AbstractDao<SceneEntity, Long> {

    public static final String TABLENAME = "SCENE_ENTITY";

    /**
     * Properties of entity SceneEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StrText = new Property(1, String.class, "strText", false, "STR_TEXT");
        public final static Property IconId = new Property(2, int.class, "iconId", false, "ICON_ID");
        public final static Property IsLight = new Property(3, boolean.class, "isLight", false, "IS_LIGHT");
        public final static Property IsAC = new Property(4, boolean.class, "isAC", false, "IS_AC");
        public final static Property IsCurtain = new Property(5, boolean.class, "isCurtain", false, "IS_CURTAIN");
        public final static Property IsBgMusic = new Property(6, boolean.class, "isBgMusic", false, "IS_BG_MUSIC");
        public final static Property IsPreTime = new Property(7, boolean.class, "isPreTime", false, "IS_PRE_TIME");
    };


    public SceneEntityDao(DaoConfig config) {
        super(config);
    }
    
    public SceneEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCENE_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"STR_TEXT\" TEXT NOT NULL ," + // 1: strText
                "\"ICON_ID\" INTEGER NOT NULL ," + // 2: iconId
                "\"IS_LIGHT\" INTEGER NOT NULL ," + // 3: isLight
                "\"IS_AC\" INTEGER NOT NULL ," + // 4: isAC
                "\"IS_CURTAIN\" INTEGER NOT NULL ," + // 5: isCurtain
                "\"IS_BG_MUSIC\" INTEGER NOT NULL ," + // 6: isBgMusic
                "\"IS_PRE_TIME\" INTEGER NOT NULL );"); // 7: isPreTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCENE_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SceneEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getStrText());
        stmt.bindLong(3, entity.getIconId());
        stmt.bindLong(4, entity.getIsLight() ? 1L: 0L);
        stmt.bindLong(5, entity.getIsAC() ? 1L: 0L);
        stmt.bindLong(6, entity.getIsCurtain() ? 1L: 0L);
        stmt.bindLong(7, entity.getIsBgMusic() ? 1L: 0L);
        stmt.bindLong(8, entity.getIsPreTime() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public SceneEntity readEntity(Cursor cursor, int offset) {
        SceneEntity entity = new SceneEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // strText
            cursor.getInt(offset + 2), // iconId
            cursor.getShort(offset + 3) != 0, // isLight
            cursor.getShort(offset + 4) != 0, // isAC
            cursor.getShort(offset + 5) != 0, // isCurtain
            cursor.getShort(offset + 6) != 0, // isBgMusic
            cursor.getShort(offset + 7) != 0 // isPreTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SceneEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStrText(cursor.getString(offset + 1));
        entity.setIconId(cursor.getInt(offset + 2));
        entity.setIsLight(cursor.getShort(offset + 3) != 0);
        entity.setIsAC(cursor.getShort(offset + 4) != 0);
        entity.setIsCurtain(cursor.getShort(offset + 5) != 0);
        entity.setIsBgMusic(cursor.getShort(offset + 6) != 0);
        entity.setIsPreTime(cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SceneEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SceneEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
