package greendao.bean;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BG_MUSIC_SELECTED_LIST_ENTITY".
 */
public class BgMusicSelectedListEntity {

    private Long id;

    private String path;

    public BgMusicSelectedListEntity() {
    }

    public BgMusicSelectedListEntity(Long id) {
        this.id = id;
    }

    public BgMusicSelectedListEntity(Long id, String path) {
        this.id = id;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath( String path) {
        this.path = path;
    }

}
